import { readFileSync, writeFileSync } from "fs";
import { join } from "path";

function embedAsBase64(path: string): string {
  const buffer = readFileSync(path);
  return buffer.toString("base64");
}

const LAYOUT_WASM_BASE64 = embedAsBase64(join(import.meta.dirname, "..", "pkg", "layout_bg.wasm"));

const output = `// AUTO-GENERATED FILE - DO NOT EDIT
// Generated by: bun run gen

export const LAYOUT_WASM_BASE64 = "${LAYOUT_WASM_BASE64}";
`;

writeFileSync(join(import.meta.dirname, "..", "ts", "gen.embedded.ts"), output);
console.log("Generated ts/gen.embedded.ts");
