import { readFileSync, writeFileSync } from "fs";
import { join } from "path";

function embedAsBase64(path: string): string {
  const buffer = readFileSync(path);
  return buffer.toString("base64");
}

const assetsDir = join(import.meta.dirname, "..", "..", "..", "assets");

const INTER_VAR_BASE64 = embedAsBase64(join(assetsDir, "InterVariable.ttf"));
const INTER_VAR_ITALIC_BASE64 = embedAsBase64(join(assetsDir, "InterVariable-Italic.ttf"));
const JETBRAINS_MONO_REGULAR_BASE64 = embedAsBase64(join(assetsDir, "JetBrainsMono-Regular.ttf"));
const NOTO_COLOR_EMOJI_REGULAR_BASE64 = embedAsBase64(
  join(assetsDir, "NotoColorEmoji-Regular.ttf")
);

const output = `// AUTO-GENERATED FILE - DO NOT EDIT
// Generated by: bun run gen

export const INTER_VAR_BASE64 = "${INTER_VAR_BASE64}";
export const INTER_VAR_ITALIC_BASE64 = "${INTER_VAR_ITALIC_BASE64}";
export const JETBRAINS_MONO_REGULAR_BASE64 = "${JETBRAINS_MONO_REGULAR_BASE64}";
export const NOTO_COLOR_EMOJI_REGULAR_BASE64 = "${NOTO_COLOR_EMOJI_REGULAR_BASE64}";
`;

writeFileSync(join(import.meta.dirname, "..", "gen.embedded.ts"), output);
console.log("Generated gen.embedded.ts");
