import { div, text } from "@glade/glade";
import type { Demo, DemoItem } from "./demo";
import { SPACER_10PX } from "./common";
import { colors } from "@glade/utils";

export const MARGIN_DEMO: Demo = {
  name: "Margin",
  renderElement: (_cx, _state): DemoItem[] => [
    text("Margin creates space outside an element.").size(16),

    // Uniform margin
    SPACER_10PX,
    text("Uniform Margin (m)").size(18).weight(600),
    div()
      .flex()
      .flexRow()
      .gap(8)
      .children(
        div()
          .bg(colors.gray.x700)
          .p(2)
          .child(
            div()
              .w(60)
              .h(40)
              .m(0)
              .bg(colors.blue.x500)
              .flex()
              .itemsCenter()
              .justifyCenter()
              .child(text("m=0").size(11))
          ),
        div()
          .bg(colors.gray.x700)
          .p(2)
          .child(
            div()
              .w(60)
              .h(40)
              .m(8)
              .bg(colors.blue.x500)
              .flex()
              .itemsCenter()
              .justifyCenter()
              .child(text("m=8").size(11))
          ),
        div()
          .bg(colors.gray.x700)
          .p(2)
          .child(
            div()
              .w(60)
              .h(40)
              .m(16)
              .bg(colors.blue.x500)
              .flex()
              .itemsCenter()
              .justifyCenter()
              .child(text("m=16").size(11))
          ),
        div()
          .bg(colors.gray.x700)
          .p(2)
          .child(
            div()
              .w(60)
              .h(40)
              .m(24)
              .bg(colors.blue.x500)
              .flex()
              .itemsCenter()
              .justifyCenter()
              .child(text("m=24").size(11))
          )
      ),

    // Horizontal margin
    SPACER_10PX,
    text("Horizontal Margin (mx)").size(18).weight(600),
    div()
      .flex()
      .flexRow()
      .gap(8)
      .children(
        div()
          .bg(colors.gray.x700)
          .py(2)
          .child(
            div()
              .w(60)
              .h(40)
              .mx(0)
              .bg(colors.green.x500)
              .flex()
              .itemsCenter()
              .justifyCenter()
              .child(text("mx=0").size(11))
          ),
        div()
          .bg(colors.gray.x700)
          .py(2)
          .child(
            div()
              .w(60)
              .h(40)
              .mx(12)
              .bg(colors.green.x500)
              .flex()
              .itemsCenter()
              .justifyCenter()
              .child(text("mx=12").size(11))
          ),
        div()
          .bg(colors.gray.x700)
          .py(2)
          .child(
            div()
              .w(60)
              .h(40)
              .mx(24)
              .bg(colors.green.x500)
              .flex()
              .itemsCenter()
              .justifyCenter()
              .child(text("mx=24").size(11))
          )
      ),

    // Vertical margin
    SPACER_10PX,
    text("Vertical Margin (my)").size(18).weight(600),
    div()
      .flex()
      .flexRow()
      .gap(8)
      .children(
        div()
          .bg(colors.gray.x700)
          .px(2)
          .child(
            div()
              .w(60)
              .h(40)
              .my(0)
              .bg(colors.purple.x500)
              .flex()
              .itemsCenter()
              .justifyCenter()
              .child(text("my=0").size(11))
          ),
        div()
          .bg(colors.gray.x700)
          .px(2)
          .child(
            div()
              .w(60)
              .h(40)
              .my(12)
              .bg(colors.purple.x500)
              .flex()
              .itemsCenter()
              .justifyCenter()
              .child(text("my=12").size(11))
          ),
        div()
          .bg(colors.gray.x700)
          .px(2)
          .child(
            div()
              .w(60)
              .h(40)
              .my(24)
              .bg(colors.purple.x500)
              .flex()
              .itemsCenter()
              .justifyCenter()
              .child(text("my=24").size(11))
          )
      ),

    // Individual margins
    SPACER_10PX,
    text("Individual Margins (mt, mr, mb, ml)").size(18).weight(600),
    div()
      .flex()
      .flexRow()
      .gap(8)
      .children(
        div()
          .bg(colors.gray.x700)
          .p(2)
          .child(
            div()
              .w(60)
              .h(40)
              .mt(16)
              .bg(colors.orange.x500)
              .flex()
              .itemsCenter()
              .justifyCenter()
              .child(text("mt=16").size(11))
          ),
        div()
          .bg(colors.gray.x700)
          .p(2)
          .child(
            div()
              .w(60)
              .h(40)
              .mr(16)
              .bg(colors.orange.x500)
              .flex()
              .itemsCenter()
              .justifyCenter()
              .child(text("mr=16").size(11))
          ),
        div()
          .bg(colors.gray.x700)
          .p(2)
          .child(
            div()
              .w(60)
              .h(40)
              .mb(16)
              .bg(colors.orange.x500)
              .flex()
              .itemsCenter()
              .justifyCenter()
              .child(text("mb=16").size(11))
          ),
        div()
          .bg(colors.gray.x700)
          .p(2)
          .child(
            div()
              .w(60)
              .h(40)
              .ml(16)
              .bg(colors.orange.x500)
              .flex()
              .itemsCenter()
              .justifyCenter()
              .child(text("ml=16").size(11))
          )
      ),
  ],
};
